### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Prasanna-kumar-Patra** [oslabs-beta/r3Dy#49]
Hi guys Nice work
Just wanted to know the roadmap

**Comment by bryanltrang** [comment]
Hi @prasanna-gmail ! 

Thank you for the compliment and for reaching out! Here's a high-level view of our roadmap.

Our upcoming enhancements include improvements to Text Fields, Sliders, Loaders, and overall performance optimizations. We’re excited to introduce even more 3D components that cover common use cases, making 3D accessible and enjoyable for all developers.

- Text Field improvements including the ability to prevent overflow in the field box
- Slider improvements including the ability to adjust default styling
- Additional Loader options and styling capabilities
- Ability to display icons on Buttons
- R3DY UI Yarn package
- Overall performance improvements and bug fixes for existing components
- A new pre-built 3D Form component
